language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn build # npm run docs:build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: .vuepress/dist
  github_token: $ACESSS_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  target_branch: https://github.com/CasbaL/casbal.github.io.git